### ISSUE TITLE
ld returns 'cannot find -ld3d11' with Winbuilds 1.5.0

### ISSUE THREAD

**Issue by seongwon-kang** [cretz/go-scrap#6]
I have `d3d11.dll` in `%System32%` folder, and there is no d3d11.o in Winbuild `lib` folder.
is there any way to compile or get d3d11 library?

**Comment by seongwon-kang** [comment]
resolved with use toolchain `MingW-W64-builds` instead of `Winbuilds`.

**Comment by jinjin123** [comment]
I was install these tool in ubuntu and mac air, but still not work....
